name: Create Release
on:
  workflow_call:
    secrets:
      npm-token:
        description: 'A npm usage token'
        required: true
      gh-token:
        description: 'A github usage token'
        required: true
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Install dependencies
        run: HUSKY_SKIP_INSTALL=1 npm ci --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
          NPM_TOKEN: ${{ secrets.npm-token }}
        run: npx semantic-release