name: Deployment

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    uses: ./.github/workflows/create-release.yml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      gh-token: ${{ secrets.MY_GH_PAT }}
    needs: [ci]