name: Publish Library to NPM and Github

on:
  release:
    types: [published]

jobs:
  publish-npm:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: HUSKY_SKIP_INSTALL=1 npm ci --ignore-scripts
      - name: Set package to False
        run: npx json -I -f package.json -e 'this.private=false'
      - name: Publish - NPM
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
      - name: Publish - Github
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish